-- INSERT INTO users (id, uuid, username, psw, email, authority, active) VALUES
--   (nextval('users_seq'), 'a3ed9a24-fd0d-11e8-8ffd-0d75412cc187', 'dpredkel',
--    '$2a$10$hPjPLxDZ7BpFkxAl4DqzauH0wn2YjcIhcIGRnUG5FWqh8qio5Eh06', 'slouchdev@gmail.com', 'ADMIN', true);
--
-- INSERT INTO runnings (id, uuid, value) VALUES
--   (nextval('runnings_seq'), 'account.margin.threshold', '0.5');
